// <auto-generated />
using System;
using KnxHelden.SHES.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnxHelden.SHES.Data.Migrations
{
    [DbContext(typeof(ShesDbContext))]
    [Migration("20250401145927_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a644771-78cf-4088-aa18-29575d0d643c"),
                            CreationTime = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModificationTime = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MDT"
                        },
                        new
                        {
                            Id = new Guid("0cf31014-48d7-4d3e-8596-ba88e7a90213"),
                            CreationTime = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModificationTime = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Siemens"
                        });
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSurname")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstructionCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstructionPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstructionStreet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.ProjectItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ProjectItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Building", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.ProjectItem");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ProjectId");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.BuildingPart", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.ProjectItem");

                    b.ToTable("BuildingParts", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Cabinet", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.ProjectItem");

                    b.ToTable("Cabinets", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Corridor", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.ProjectItem");

                    b.ToTable("Corridors", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Device", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.ProjectItem");

                    b.Property<int>("BusType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DivisionUnits")
                        .HasColumnType("REAL");

                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRailMounted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KnxTopologyAddress")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KnxTopologyArea")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KnxTopologyLine")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Floor", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.ProjectItem");

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Room", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.ProjectItem");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Stair", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.ProjectItem");

                    b.ToTable("Stairs", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.BinaryInput", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.Device");

                    b.Property<int>("ChannelNames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.ToTable("BinaryInputs", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.BlindActuator", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.Device");

                    b.Property<int>("ChannelNames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.ToTable("BlindActuators", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.BusPowerSupply", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.Device");

                    b.Property<ushort>("Power")
                        .HasColumnType("INTEGER");

                    b.ToTable("BusPowerSupplys", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.DimmingActuator", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.Device");

                    b.Property<int>("ChannelNames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.ToTable("DimmingActuators", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.HeatingActuator", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.Device");

                    b.Property<int>("ChannelNames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.ToTable("HeatingActuators", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.SwitchingActuator", b =>
                {
                    b.HasBaseType("KnxHelden.SHES.Models.Entities.Device");

                    b.Property<int>("ChannelNames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.ToTable("SwitchingActuators", (string)null);
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.ProjectItem", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Building", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.Building", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnxHelden.SHES.Models.Entities.Project", "Project")
                        .WithMany("Buildings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.BuildingPart", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.BuildingPart", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Cabinet", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.Cabinet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Corridor", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.Corridor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Device", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.Device", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnxHelden.SHES.Models.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Devices")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Floor", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.Floor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Room", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.Room", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Stair", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.ProjectItem", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.Stair", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.BinaryInput", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.BinaryInput", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.BlindActuator", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.BlindActuator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.BusPowerSupply", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.BusPowerSupply", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.DimmingActuator", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.DimmingActuator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.HeatingActuator", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.HeatingActuator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.SwitchingActuator", b =>
                {
                    b.HasOne("KnxHelden.SHES.Models.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("KnxHelden.SHES.Models.Entities.SwitchingActuator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Manufacturer", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.Project", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("KnxHelden.SHES.Models.Entities.ProjectItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
